### ISSUE TITLE
import winreg

### ISSUE THREAD

**Issue by sec13b** [ConradSun/RDP-Password-checker#2]
└─# python3 weakpwd_rdp.py
Traceback (most recent call last):
  File "/root/RDP-Password-checker/weakpwd_rdp.py", line 6, in <module>
    import winreg
ModuleNotFoundError: No module named 'winreg'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
python3 -V
Python 3.11.2
~~~~~~~~~~~~~~~~~~~~~~~~~
can you help ?

**Comment by ConradSun** [comment]
The purpose of the project is to crack the login password of Windows system, not Linux system.

**Comment by ConradSun** [comment]
The purpose of the project is to crack the login password of Windows system, not Linux system.

**Comment by sec13b** [comment]
OK
