### ISSUE TITLE
failed in dumping hive file

### ISSUE THREAD

**Issue by sec13b** [ConradSun/RDP-Password-checker#3]
192.168.0.205 ip is from local network

C:\Users\user\Desktop\RDP-Password-checker>python weakpwd_rdp.py 192.168.0.205
[+] [RDP] failed in dumping hive file: ERROR: The system was unable to find the specified registry key or value.
[-] [RDP] CmdCallError occured.

**Comment by ConradSun** [comment]
已修复无法dump注册表的问题
cd到工程目录
python .\weakpwd_rdp.py 即可
本机模拟登陆，不需要添加ip作为参数

**Comment by ConradSun** [comment]
You can try the new code. The bug may have been fixed.
